services:
  - type: web
    name: users-management-taller-dylan
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /v3/api-docs
    envVars:
      - key: SERVER_FORWARD_HEADERS_STRATEGY
        value: framework
      - key: DB_ENGINE
        value: postgresql
      - key: DB_POOL_SIZE
        value: "2"
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:InitialRAMPercentage=20 -XX:MaxRAMPercentage=65"
      - key: EMAIL_PROVIDER
        value: gmail-api
      - key: SMTP_FROM_ADDRESS
        sync: false
      - key: SMTP_FROM_NAME
        value: Gestion de Usuarios - Taller
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
